define([
	'./services/apinetService',
	'./services/coreConfig',
	'./services/dictionaryService',
	'./services/filteringService',
	'./services/helpers',
	'./services/i18n',
	'./services/metadataService',
	'./services/moduleConfig',
	'./services/pageConfig',
	'./services/reportService'
]);